# Generated by Django 4.2.7 on 2023-11-11 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_user_groups_user_is_superuser_user_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Userform',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
