# Generated by Django 4.2.7 on 2023-11-14 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_product_mfd_product_return_policy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='warrenty',
            field=models.CharField(blank=True, default='1', max_length=100, null=True),
        ),
    ]
