# Generated by Django 4.2.7 on 2023-11-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_product_warrenty'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cod',
            field=models.BooleanField(default=True),
        ),
    ]
