# Generated by Django 4.2.7 on 2023-11-17 18:00

import app1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_product_cod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='product.jpg', null=True, upload_to=app1.models.user_directory_path),
        ),
    ]
