# Generated by Django 4.2.7 on 2023-11-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_size_varients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='varients',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='varient',
            field=models.CharField(choices=[('None', 'None'), ('Size', 'Size')], default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='varients',
            name='image_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
