# Generated by Django 4.2.7 on 2023-11-27 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_rename_varients_variants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='value',
            field=models.CharField(blank=True, default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='variants',
            name='image_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.productimages'),
        ),
    ]
