# Generated by Django 4.2.7 on 2023-12-22 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0031_productreview_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='wallet_status',
            field=models.BooleanField(default=False),
        ),
    ]
