# Generated by Django 4.2.7 on 2023-12-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0035_userdetails_code_userdetails_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='referral',
            field=models.BooleanField(default=False),
        ),
    ]
