# Generated by Django 4.2.7 on 2023-12-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0036_wallet_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
